d={}
name=input("enter friend name ")
lang=input("enter friend  lang ")
d.update({name:lang})
name=input("enter friend name ")
lang=input("enter friend lang ")
d.update({name:lang})
name=input("enter friend name ")
lang=input("enter friend lang ")
d.update({name:lang})
name=input("enter friend name ")
lang=input("enter friend lang ")
d.update({name:lang})
print(d)